---
name: justbases CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  development_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: pylint python3-hypothesis python3-setuptools
            task: PYTHONPATH=./src make -f Makefile lint
          - dependencies: python3-hypothesis python3-setuptools
            task: PYTHONPATH=./src make -f Makefile test
          - dependencies: python3-coverage python3-hypothesis python3-setuptools
            task: PYTHONPATH=./src make -f Makefile coverage
          - dependencies: python python3-build twine
            task: make -f Makefile package
    runs-on: ubuntu-latest
    container: fedora:42  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: Run ${{ matrix.task }}
        run: ${{ matrix.task }}

  lowest_supported_python:
    strategy:
      matrix:
        include:
          - dependencies: python3-hypothesis
            task: PYTHONPATH=./src make -f Makefile test
    runs-on: ubuntu-latest
    container: fedora:42  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - name: Install python3.12
        run: >
          dnf install -y
          alternatives
          python3.12
      - name: Set python3 to python3.12
        run: >
          alternatives
          --install /usr/bin/python3
          python3
          /usr/bin/python3.12
          10
      - name: Display Python version
        run: python3 --version
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: Run ${{ matrix.task }}
        run: ${{ matrix.task }}
